// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate with email and password, returns a JWT Bearer token. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token and user info",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates every JWT issued before now for this user, including the one used to call this endpoint — the client should discard its token and redirect to login. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out of all devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Changes the authenticated user's password after verifying the current one. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Current and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Current password is incorrect",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the authenticated user's profile name and phone number. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update profile",
                "parameters": [
                    {
                        "description": "Profile update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/profile/picture": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads a profile picture (jpg, png, or webp — max 5 MB). Replaces any existing picture. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Upload profile picture",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Profile picture file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Storage not configured",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account with name, email, and password. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Aggregated stats backing the main dashboard: headline, summary metrics, sentiment trend, per-platform volume, top keywords, topic distribution, and top sentiment drivers all combine posts AND comments (see repository.PostRepository's Combined* methods) — unlike /mentions, which is post-only. recent_mentions is the one exception and stays post-only (a bare comment has no url/location/category of its own). topic_distribution/keyword_cloud/drivers are keyword-matched, not a stored classification — see service.ClassifyTopics/computeDrivers. summary.*.change is always \"-\" — period-over-period comparison isn't implemented. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard overview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, WIB) — omit for no lower bound",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, WIB, inclusive) — omit for no upper bound",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ingest/posts": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Internal endpoint for the Python sentiment-labeling worker. Upserts by (platform, platform_post_id, published_at); re-ingesting an existing post refreshes engagement counters but never overwrites an already-set sentiment. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest a crawled (optionally labeled) post with its comments",
                "parameters": [
                    {
                        "description": "Post + comments payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.IngestPostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/keywords": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Top keywords extracted from posts+comments (see service.ExtractKeywordStats), with q/sentiment filtering the already-extracted list rather than re-running extraction. growth is always \"-\" and alerts is always empty — both need a period-over-period comparison the ingested data (currently ~4 days) can't yet support meaningfully. stats.* reflect the whole tracked set, not just the filtered items. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keywords"
                ],
                "summary": "List tracked keywords",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Free-text filter on keyword text",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "positive, negative, neutral, or \\",
                        "name": "sentiment",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, WIB) — omit for no lower bound",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, WIB, inclusive) — omit for no upper bound",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mentions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists sentiment-labeled posts for the monitoring dashboard, with metrics and per-platform volume aggregated over the whole filtered set. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mentions"
                ],
                "summary": "List mentions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Free-text search in content/author",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "X, Instagram, TikTok, News, YouTube, or \\",
                        "name": "platform",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "positive, negative, neutral, or \\",
                        "name": "sentiment",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, WIB) — omit for no lower bound",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, WIB, inclusive) — omit for no upper bound",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mentions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single sentiment-labeled mention. 404s if the post exists but hasn't been labeled yet. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mentions"
                ],
                "summary": "Get mention detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sentiment/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Aggregated sentiment stats backing the Sentiment Analysis page: score, summary metrics, distribution, trend, per-platform and per-category breakdowns. Combines posts AND comments (see repository.PostRepository's Combined* methods), like /dashboard/overview — unlike /mentions, which is post-only. by_category is keyword-matched (service.ClassifyTopicSentiment), not a stored classification. summary.*.change is always \"-\" — period-over-period comparison isn't implemented. Response messages are localized via ?lang= or Accept-Language (id/en).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sentiment"
                ],
                "summary": "Sentiment overview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, WIB) — omit for no lower bound",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, WIB, inclusive) — omit for no upper bound",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "handler.IngestCommentRequest": {
            "type": "object",
            "required": [
                "platform_comment_id",
                "published_at"
            ],
            "properties": {
                "author_handle": {
                    "type": "string"
                },
                "content": {
                    "description": "Content is not required — a comment can legitimately have no text\n(sticker/image-only comment).",
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "model_version": {
                    "type": "string"
                },
                "platform_comment_id": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "raw_payload": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sentiment": {
                    "enum": [
                        "positive",
                        "negative",
                        "neutral"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Sentiment"
                        }
                    ]
                },
                "sentiment_score": {
                    "type": "number"
                }
            }
        },
        "handler.IngestPostRequest": {
            "type": "object",
            "required": [
                "crawled_at",
                "platform",
                "platform_post_id",
                "published_at"
            ],
            "properties": {
                "author_handle": {
                    "type": "string"
                },
                "author_name": {
                    "type": "string"
                },
                "comment_count": {
                    "type": "integer"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.IngestCommentRequest"
                    }
                },
                "content": {
                    "description": "Content is not required — a post can legitimately have no caption\n(video/image-only post).",
                    "type": "string"
                },
                "crawled_at": {
                    "type": "string"
                },
                "like_count": {
                    "type": "integer"
                },
                "model_version": {
                    "type": "string"
                },
                "platform": {
                    "enum": [
                        "x",
                        "instagram",
                        "tiktok",
                        "youtube",
                        "news"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Platform"
                        }
                    ]
                },
                "platform_post_id": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "raw_payload": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sentiment": {
                    "enum": [
                        "positive",
                        "negative",
                        "neutral"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Sentiment"
                        }
                    ]
                },
                "sentiment_score": {
                    "type": "number"
                },
                "share_count": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "view_count": {
                    "type": "integer"
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handler.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone_number"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8
                }
            }
        },
        "handler.UpdateProfileRequest": {
            "type": "object",
            "required": [
                "name",
                "phone_number"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8
                }
            }
        },
        "model.Platform": {
            "type": "string",
            "enum": [
                "x",
                "instagram",
                "tiktok",
                "youtube",
                "news"
            ],
            "x-enum-varnames": [
                "PlatformX",
                "PlatformInstagram",
                "PlatformTikTok",
                "PlatformYouTube",
                "PlatformNews"
            ]
        },
        "model.Sentiment": {
            "type": "string",
            "enum": [
                "positive",
                "negative",
                "neutral"
            ],
            "x-enum-varnames": [
                "SentimentPositive",
                "SentimentNegative",
                "SentimentNeutral"
            ]
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Shared secret for the internal ingest routes (Python labeling worker)",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "Enter: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PawonWarga API",
	Description:      "PawonWarga Backend API Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
